export const NotificationType = {
    FOLLOW: "FOLLOW",
    COURSE_SUBSCRIBE: "COURSE_SUBSCRIBE",
    COURSE_REVIEW: "COURSE_REVIEW",
    POST_RATE: "POST_RATE",
    POST_DISCUSSION: "POST_DISCUSSION",
    FOLLOWING_NEW_COURSE: "FOLLOWING_NEW_COURSE",
    FOLLOWING_NEW_POST: "FOLLOWING_NEW_POST",
    SUBSCRIBED_CREATOR_NEW_COURSE: "SUBSCRIBED_CREATOR_NEW_COURSE",
    SUBSCRIBED_CREATOR_NEW_POST: "SUBSCRIBED_CREATOR_NEW_POST",
    MODERATION_ALERT: "MODERATION_ALERT",
    ADMIN_WARNING: "ADMIN_WARNING",
} as const;

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];
