-- Seed a broad online-learning skill taxonomy. The canonical names follow
-- commonly used industry/product names; aliases cover abbreviations and
-- frequent spelling, punctuation, spacing, and search variations.
ALTER TABLE "skill_alias"
DROP CONSTRAINT IF EXISTS "skill_alias_skillId_fkey";

ALTER TABLE "skill_alias"
ADD CONSTRAINT "skill_alias_skillId_fkey"
FOREIGN KEY ("skillId") REFERENCES "skill"("id")
ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS "skill_alias_skillId_idx" ON "skill_alias"("skillId");

CREATE TEMP TABLE "_skill_seed" (
    "name" TEXT PRIMARY KEY
);

INSERT INTO "_skill_seed" ("name") VALUES
-- Programming languages and foundations
('Python'),
('JavaScript'),
('TypeScript'),
('Java'),
('C'),
('C++'),
('C#'),
('Go'),
('Rust'),
('PHP'),
('Ruby'),
('Kotlin'),
('Swift'),
('Dart'),
('R'),
('MATLAB'),
('Scala'),
('Perl'),
('Lua'),
('Haskell'),
('Elixir'),
('Erlang'),
('Clojure'),
('F#'),
('Visual Basic .NET'),
('Objective-C'),
('Groovy'),
('Julia'),
('Solidity'),
('Bash'),
('PowerShell'),
('Assembly Language'),
('COBOL'),
('Fortran'),
('Prolog'),
('OCaml'),
('Delphi'),
('VHDL'),
('Verilog'),
('Scratch'),
('Programming Fundamentals'),
('Object-Oriented Programming'),
('Functional Programming'),
('Concurrent Programming'),
('Asynchronous Programming'),
('Data Structures'),
('Algorithms'),
('Computational Thinking'),
('Regular Expressions'),
('Design Patterns'),

-- Web and frontend development
('HTML5'),
('CSS3'),
('Sass'),
('Less'),
('Tailwind CSS'),
('Bootstrap'),
('ReactJS'),
('Next.js'),
('Vue.js'),
('Nuxt.js'),
('Angular'),
('Svelte'),
('SvelteKit'),
('jQuery'),
('Redux'),
('Zustand'),
('RxJS'),
('Web Components'),
('Responsive Web Design'),
('Web Accessibility'),
('Progressive Web Apps'),
('Single-Page Applications'),
('Server-Side Rendering'),
('Static Site Generation'),
('Web Performance Optimization'),
('Browser Developer Tools'),
('DOM Manipulation'),
('Webpack'),
('Vite'),
('Babel'),
('ESLint'),
('npm'),
('Yarn'),
('pnpm'),
('Storybook'),
('Material UI'),
('Chakra UI'),
('Ant Design'),
('Three.js'),
('D3.js'),
('WebGL'),
('WordPress'),
('Shopify Development'),
('Webflow'),
('Elementor'),
('Frontend Development'),
('Web Design'),

-- Backend, API, and distributed systems
('Node.js'),
('Express.js'),
('NestJS'),
('Fastify'),
('Django'),
('Flask'),
('FastAPI'),
('Spring Boot'),
('ASP.NET Core'),
('Ruby on Rails'),
('Laravel'),
('Symfony'),
('Phoenix Framework'),
('Gin'),
('Fiber'),
('GraphQL'),
('REST API Design'),
('gRPC'),
('WebSockets'),
('OAuth 2.0'),
('OpenID Connect'),
('JSON Web Tokens'),
('API Security'),
('API Testing'),
('Microservices'),
('Event-Driven Architecture'),
('Domain-Driven Design'),
('Message Queues'),
('Apache Kafka'),
('RabbitMQ'),
('Apache Pulsar'),
('Backend Development'),
('Distributed Systems'),
('System Design'),
('Serverless Computing'),
('Caching Strategies'),
('Load Balancing'),
('Webhooks'),
('OpenAPI'),
('Postman'),

-- Mobile, desktop, games, and immersive development
('Android Development'),
('iOS Development'),
('React Native'),
('Flutter'),
('SwiftUI'),
('Jetpack Compose'),
('Xamarin'),
('Ionic'),
('Kotlin Multiplatform'),
('Mobile UI Design'),
('Mobile App Testing'),
('Electron'),
('Windows App Development'),
('macOS App Development'),
('Qt'),
('Unity'),
('Unreal Engine'),
('Godot Engine'),
('Game Design'),
('Game Programming'),
('Level Design'),
('Virtual Reality Development'),
('Augmented Reality Development'),
('Mixed Reality Development'),
('Roblox Studio'),

-- Databases, analytics, and data engineering
('SQL'),
('PostgreSQL'),
('MySQL'),
('Microsoft SQL Server'),
('Oracle Database'),
('SQLite'),
('MongoDB'),
('Redis'),
('Elasticsearch'),
('OpenSearch'),
('Apache Cassandra'),
('DynamoDB'),
('Firebase'),
('Supabase'),
('Neo4j'),
('MariaDB'),
('Snowflake'),
('Google BigQuery'),
('Amazon Redshift'),
('Databricks'),
('Apache Spark'),
('Apache Hadoop'),
('Apache Flink'),
('Apache Airflow'),
('dbt'),
('Data Modeling'),
('Database Design'),
('Database Administration'),
('Data Warehousing'),
('Data Lakes'),
('Data Pipelines'),
('ETL Development'),
('Data Cleaning'),
('Data Transformation'),
('Data Governance'),
('Data Quality'),
('Master Data Management'),
('Business Intelligence'),
('Data Analytics'),
('Data Visualization'),
('Exploratory Data Analysis'),
('Statistical Analysis'),
('A/B Testing'),
('Tableau'),
('Microsoft Power BI'),
('Looker'),
('Qlik Sense'),
('Microsoft Excel'),
('Google Sheets'),
('Power Query'),
('DAX'),
('Pandas'),
('NumPy'),

-- Artificial intelligence and machine learning
('Artificial Intelligence'),
('Machine Learning'),
('Deep Learning'),
('Generative AI'),
('Large Language Models'),
('Natural Language Processing'),
('Computer Vision'),
('Reinforcement Learning'),
('Supervised Learning'),
('Unsupervised Learning'),
('Feature Engineering'),
('Model Evaluation'),
('Model Fine-Tuning'),
('Prompt Engineering'),
('Retrieval-Augmented Generation'),
('AI Agents'),
('Model Context Protocol'),
('Vector Databases'),
('Semantic Search'),
('Recommendation Systems'),
('Time Series Forecasting'),
('Anomaly Detection'),
('Speech Recognition'),
('Text-to-Speech'),
('AI Ethics'),
('Responsible AI'),
('MLOps'),
('TensorFlow'),
('PyTorch'),
('Keras'),
('scikit-learn'),
('Hugging Face Transformers'),
('OpenCV'),
('LangChain'),
('LlamaIndex'),
('ONNX'),
('XGBoost'),
('LightGBM'),
('Neural Networks'),
('Convolutional Neural Networks'),
('Recurrent Neural Networks'),
('Transformers'),
('Diffusion Models'),
('Data Science'),
('Applied Statistics'),
('Bayesian Statistics'),
('Operations Research'),
('Linear Algebra'),
('Calculus'),
('Probability'),

-- Cloud, DevOps, platform, and reliability engineering
('Amazon Web Services'),
('Microsoft Azure'),
('Google Cloud Platform'),
('Docker'),
('Kubernetes'),
('Terraform'),
('Ansible'),
('Puppet'),
('Chef'),
('Helm'),
('Jenkins'),
('GitHub Actions'),
('GitLab CI/CD'),
('CircleCI'),
('Argo CD'),
('Azure DevOps'),
('Continuous Integration'),
('Continuous Delivery'),
('Infrastructure as Code'),
('Cloud Architecture'),
('Cloud Security'),
('Cloud Cost Optimization'),
('Site Reliability Engineering'),
('Platform Engineering'),
('DevOps'),
('DevSecOps'),
('Linux Administration'),
('Windows Server Administration'),
('Nginx'),
('Apache HTTP Server'),
('Prometheus'),
('Grafana'),
('Datadog'),
('New Relic'),
('Splunk'),
('OpenTelemetry'),
('Observability'),
('Log Management'),
('Incident Management'),
('Chaos Engineering'),
('Release Management'),
('Configuration Management'),
('FinOps'),
('Edge Computing'),
('Cloud Migration'),

-- Cybersecurity, networking, and IT operations
('Cybersecurity Fundamentals'),
('Network Security'),
('Application Security'),
('Information Security Management'),
('Security Operations'),
('Ethical Hacking'),
('Penetration Testing'),
('Vulnerability Assessment'),
('Threat Modeling'),
('Threat Intelligence'),
('Digital Forensics'),
('Incident Response'),
('Malware Analysis'),
('Reverse Engineering'),
('Identity and Access Management'),
('Zero Trust Security'),
('Cryptography'),
('Secure Coding'),
('OWASP Top 10'),
('Security Information and Event Management'),
('SOC Operations'),
('Risk Assessment'),
('Governance, Risk, and Compliance'),
('ISO 27001'),
('NIST Cybersecurity Framework'),
('CompTIA A+'),
('CompTIA Network+'),
('CompTIA Security+'),
('Cisco Networking'),
('TCP/IP'),
('DNS'),
('Virtual Private Networks'),
('Network Administration'),
('Wireless Networking'),
('Firewall Administration'),
('Active Directory'),
('Microsoft 365 Administration'),
('Google Workspace Administration'),
('IT Support'),
('Help Desk Support'),
('Hardware Troubleshooting'),
('Operating Systems'),
('Linux'),
('Windows'),
('macOS'),

-- Software engineering, quality, and product delivery
('Git'),
('GitHub'),
('GitLab'),
('Bitbucket'),
('Version Control'),
('Agile Software Development'),
('Scrum'),
('Kanban'),
('Lean Software Development'),
('Software Architecture'),
('Clean Architecture'),
('SOLID Principles'),
('Refactoring'),
('Code Review'),
('Technical Documentation'),
('Unit Testing'),
('Integration Testing'),
('End-to-End Testing'),
('Test-Driven Development'),
('Behavior-Driven Development'),
('Quality Assurance'),
('Test Automation'),
('Selenium'),
('Cypress'),
('Playwright'),
('Jest'),
('Vitest'),
('JUnit'),
('Pytest'),
('Performance Testing'),
('Load Testing'),
('Accessibility Testing'),
('Software Debugging'),
('Software Maintenance'),
('Legacy System Modernization'),
('Product Management'),
('Product Strategy'),
('Product Discovery'),
('Product Roadmapping'),
('Requirements Engineering'),
('Business Analysis'),
('User Story Writing'),
('Jira'),
('Confluence'),
('Notion'),
('Technical Leadership'),

-- Electrical, mechanical, civil, and industrial engineering
('AutoCAD'),
('SOLIDWORKS'),
('Autodesk Inventor'),
('Fusion 360'),
('CATIA'),
('Siemens NX'),
('Creo Parametric'),
('Revit'),
('SketchUp'),
('Civil 3D'),
('Building Information Modeling'),
('Computer-Aided Design'),
('Computer-Aided Manufacturing'),
('Finite Element Analysis'),
('Computational Fluid Dynamics'),
('Geometric Dimensioning and Tolerancing'),
('Mechanical Design'),
('Machine Design'),
('Engineering Drawing'),
('Materials Science'),
('Thermodynamics'),
('Fluid Mechanics'),
('Heat Transfer'),
('Statics'),
('Dynamics'),
('Strength of Materials'),
('Electrical Engineering'),
('Circuit Design'),
('Digital Electronics'),
('Analog Electronics'),
('PCB Design'),
('Embedded Systems'),
('Arduino'),
('Raspberry Pi'),
('Microcontroller Programming'),
('Programmable Logic Controllers'),
('Industrial Automation'),
('Robotics'),
('Control Systems'),
('Signal Processing'),
('Power Systems'),
('Renewable Energy Systems'),
('Solar Energy Design'),
('Structural Engineering'),
('Civil Engineering'),
('Construction Management'),
('Surveying'),
('Geographic Information Systems'),
('ArcGIS'),
('QGIS'),
('Environmental Engineering'),
('Chemical Engineering'),
('Process Engineering'),
('Manufacturing Engineering'),
('Lean Manufacturing'),
('Six Sigma'),
('CNC Machining'),
('3D Printing'),
('Welding'),
('Quality Control'),
('Supply Chain Engineering'),
('Systems Engineering'),

-- Business, management, operations, and entrepreneurship
('Project Management'),
('Program Management'),
('Portfolio Management'),
('Operations Management'),
('Strategic Management'),
('Business Strategy'),
('Corporate Strategy'),
('Competitive Analysis'),
('Market Research'),
('Business Model Design'),
('Business Planning'),
('Entrepreneurship'),
('Startup Management'),
('Innovation Management'),
('Change Management'),
('Organizational Development'),
('Leadership'),
('Team Management'),
('People Management'),
('Performance Management'),
('Decision-Making'),
('Problem-Solving'),
('Critical Thinking'),
('Design Thinking'),
('Systems Thinking'),
('Process Improvement'),
('Business Process Management'),
('Risk Management'),
('Crisis Management'),
('Stakeholder Management'),
('Vendor Management'),
('Procurement'),
('Contract Management'),
('Supply Chain Management'),
('Logistics Management'),
('Inventory Management'),
('Demand Planning'),
('Quality Management'),
('Human Resource Management'),
('Talent Acquisition'),
('Recruiting'),
('Employee Relations'),
('Learning and Development'),
('Compensation and Benefits'),
('Workforce Planning'),
('Diversity, Equity, and Inclusion'),
('Corporate Governance'),
('Business Ethics'),
('Sustainability Management'),
('Environmental, Social, and Governance'),
('OKRs'),
('Balanced Scorecard'),
('Management Consulting'),

-- Finance, accounting, economics, and legal skills
('Financial Accounting'),
('Managerial Accounting'),
('Bookkeeping'),
('Financial Reporting'),
('Financial Statement Analysis'),
('Corporate Finance'),
('Financial Modeling'),
('Valuation'),
('Investment Analysis'),
('Risk Analysis'),
('Budgeting'),
('Forecasting'),
('Cost Accounting'),
('Tax Accounting'),
('Auditing'),
('International Financial Reporting Standards'),
('Generally Accepted Accounting Principles'),
('QuickBooks'),
('Xero'),
('SAP S/4HANA'),
('Enterprise Resource Planning'),
('Payroll Administration'),
('Personal Finance'),
('Investing'),
('Stock Trading'),
('Options Trading'),
('Foreign Exchange Trading'),
('Cryptocurrency'),
('Blockchain'),
('Decentralized Finance'),
('Economics'),
('Microeconomics'),
('Macroeconomics'),
('Econometrics'),
('Commercial Law'),
('Contract Law'),
('Intellectual Property'),
('Data Privacy'),
('Regulatory Compliance'),

-- Marketing, sales, communication, and customer success
('Digital Marketing'),
('Content Marketing'),
('Social Media Marketing'),
('Search Engine Optimization'),
('Search Engine Marketing'),
('Email Marketing'),
('Affiliate Marketing'),
('Influencer Marketing'),
('Performance Marketing'),
('Growth Marketing'),
('Product Marketing'),
('Brand Management'),
('Brand Strategy'),
('Marketing Strategy'),
('Marketing Analytics'),
('Google Analytics'),
('Google Ads'),
('Meta Ads'),
('LinkedIn Ads'),
('TikTok Marketing'),
('YouTube Marketing'),
('Conversion Rate Optimization'),
('Copywriting'),
('Content Strategy'),
('Storytelling'),
('Public Relations'),
('Media Planning'),
('Marketing Automation'),
('HubSpot'),
('Salesforce'),
('Customer Relationship Management'),
('Sales'),
('Sales Management'),
('B2B Sales'),
('B2C Sales'),
('Consultative Selling'),
('Lead Generation'),
('Prospecting'),
('Sales Negotiation'),
('Account Management'),
('Customer Success'),
('Customer Service'),
('Customer Experience'),
('Community Management'),
('E-commerce'),
('Retail Management'),

-- User experience, design, art, and creative production
('User Experience Design'),
('User Interface Design'),
('Interaction Design'),
('User Research'),
('Usability Testing'),
('Information Architecture'),
('Wireframing'),
('Prototyping'),
('Figma'),
('Sketch'),
('Adobe XD'),
('Design Systems'),
('Service Design'),
('Human-Centered Design'),
('Graphic Design'),
('Visual Design'),
('Logo Design'),
('Brand Identity Design'),
('Typography'),
('Color Theory'),
('Layout Design'),
('Adobe Photoshop'),
('Adobe Illustrator'),
('Adobe InDesign'),
('Affinity Designer'),
('Canva'),
('Digital Illustration'),
('Drawing'),
('Sketching'),
('Painting'),
('Watercolor Painting'),
('Acrylic Painting'),
('Oil Painting'),
('Concept Art'),
('Character Design'),
('Storyboard Art'),
('Comic Art'),
('Calligraphy'),
('Hand Lettering'),
('Fashion Design'),
('Interior Design'),
('Landscape Design'),
('Architecture'),
('3D Modeling'),
('3D Sculpting'),
('Blender'),
('Autodesk Maya'),
('3ds Max'),
('Cinema 4D'),
('ZBrush'),
('Substance 3D Painter'),
('3D Rendering'),
('Motion Graphics'),
('2D Animation'),
('3D Animation'),
('Character Animation'),
('Rigging'),
('Visual Effects'),

-- Photography, video, audio, and music
('Photography'),
('Portrait Photography'),
('Landscape Photography'),
('Product Photography'),
('Street Photography'),
('Wedding Photography'),
('Photo Editing'),
('Photo Retouching'),
('Adobe Lightroom'),
('Composition'),
('Lighting'),
('Videography'),
('Video Production'),
('Video Editing'),
('Adobe Premiere Pro'),
('Final Cut Pro'),
('DaVinci Resolve'),
('Cinematography'),
('Screenwriting'),
('Video Color Grading'),
('Podcast Production'),
('Audio Editing'),
('Audio Engineering'),
('Sound Design'),
('Music Production'),
('Music Theory'),
('Songwriting'),
('Music Composition'),
('Ableton Live'),
('FL Studio'),
('Logic Pro'),
('Pro Tools'),
('GarageBand'),
('Singing'),
('Piano'),
('Guitar'),
('Bass Guitar'),
('Drums'),
('Violin'),
('DJing'),

-- Writing, education, research, and languages
('Academic Writing'),
('Business Writing'),
('Technical Writing'),
('Creative Writing'),
('Content Writing'),
('Grant Writing'),
('Resume Writing'),
('Editing and Proofreading'),
('Journalism'),
('Research Methods'),
('Qualitative Research'),
('Quantitative Research'),
('Survey Design'),
('Literature Review'),
('Scientific Writing'),
('Instructional Design'),
('Curriculum Development'),
('Lesson Planning'),
('Online Teaching'),
('Classroom Management'),
('Adult Learning'),
('Corporate Training'),
('Coaching'),
('Mentoring'),
('English'),
('Spanish'),
('French'),
('German'),
('Italian'),
('Portuguese'),
('Mandarin Chinese'),
('Japanese'),
('Korean'),
('Arabic'),
('Hindi'),
('Russian'),
('English Grammar'),
('English Pronunciation'),
('English as a Second Language'),
('Sign Language'),

-- Health, fitness, lifestyle, and practical skills
('Anatomy'),
('Physiology'),
('Nutrition'),
('Public Health'),
('Epidemiology'),
('Health Informatics'),
('Medical Terminology'),
('First Aid'),
('Cardiopulmonary Resuscitation'),
('Mental Health Awareness'),
('Psychology'),
('Counselling Skills'),
('Mindfulness'),
('Meditation'),
('Stress Management'),
('Yoga'),
('Pilates'),
('Strength Training'),
('Personal Training'),
('Running'),
('Sports Coaching'),
('Cooking'),
('Baking'),
('Cake Decorating'),
('Coffee Brewing'),
('Bartending'),
('Gardening'),
('Sustainable Gardening'),
('Woodworking'),
('Carpentry'),
('Home Improvement'),
('Electrical Wiring'),
('Plumbing'),
('Automotive Repair'),
('Sewing'),
('Knitting'),
('Crochet'),
('Jewelry Making'),
('Pottery'),
('Ceramics'),

-- Professional and interpersonal skills
('Communication'),
('Public Speaking'),
('Presentation Skills'),
('Active Listening'),
('Interpersonal Communication'),
('Cross-Cultural Communication'),
('Business Communication'),
('Emotional Intelligence'),
('Conflict Resolution'),
('Negotiation'),
('Persuasion'),
('Facilitation'),
('Collaboration'),
('Teamwork'),
('Networking'),
('Time Management'),
('Productivity'),
('Goal Setting'),
('Self-Management'),
('Adaptability'),
('Resilience'),
('Creativity'),
('Innovation'),
('Analytical Thinking'),
('Strategic Thinking'),
('Decision Analysis'),
('Career Development'),
('Job Searching'),
('Interviewing'),
('Personal Branding'),
('Remote Work'),
('Meeting Management'),
('Workplace Ethics'),
('Workplace Safety'),
('Entrepreneurial Mindset');

INSERT INTO "skill" ("name")
SELECT "name"
FROM "_skill_seed"
ON CONFLICT ("name") DO NOTHING;

-- Important semantic and industry-standard aliases take priority over the
-- generated punctuation/search variants below.
CREATE TEMP TABLE "_skill_alias_override" (
    "skillName" TEXT NOT NULL,
    "alias" TEXT NOT NULL,
    PRIMARY KEY ("skillName", "alias")
);

INSERT INTO "_skill_alias_override" ("skillName", "alias") VALUES
('ReactJS', 'React'), ('ReactJS', 'React.js'), ('ReactJS', 'React JS'),
('JavaScript', 'JS'), ('JavaScript', 'ECMAScript'), ('JavaScript', 'Java Script'),
('TypeScript', 'TS'), ('TypeScript', 'Type Script'), ('TypeScript', 'Typed JavaScript'),
('Node.js', 'Node'), ('Node.js', 'NodeJS'), ('Node.js', 'Node JS'),
('Next.js', 'NextJS'), ('Next.js', 'Next JS'), ('Next.js', 'Next'),
('Vue.js', 'Vue'), ('Vue.js', 'VueJS'), ('Vue.js', 'Vue JS'),
('Nuxt.js', 'Nuxt'), ('Nuxt.js', 'NuxtJS'), ('Nuxt.js', 'Nuxt JS'),
('Express.js', 'Express'), ('Express.js', 'ExpressJS'), ('Express.js', 'Express JS'),
('C++', 'CPP'), ('C++', 'C Plus Plus'), ('C++', 'Cplusplus'),
('C#', 'C Sharp'), ('C#', 'C-Sharp'), ('C#', 'Dotnet C#'),
('Visual Basic .NET', 'VB.NET'), ('Visual Basic .NET', 'VB Net'), ('Visual Basic .NET', 'Visual Basic Dotnet'),
('Objective-C', 'Obj-C'), ('Objective-C', 'Objective C'), ('Objective-C', 'ObjC'),
('Amazon Web Services', 'AWS'), ('Amazon Web Services', 'Amazon Cloud'), ('Amazon Web Services', 'AWS Cloud'),
('Google Cloud Platform', 'GCP'), ('Google Cloud Platform', 'Google Cloud'), ('Google Cloud Platform', 'G Cloud'),
('Microsoft Azure', 'Azure'), ('Microsoft Azure', 'Azure Cloud'), ('Microsoft Azure', 'MS Azure'),
('Kubernetes', 'K8s'), ('Kubernetes', 'Kube'), ('Kubernetes', 'Container Orchestration'),
('Infrastructure as Code', 'IaC'), ('Infrastructure as Code', 'Infra as Code'), ('Infrastructure as Code', 'Infrastructure-as-Code'),
('Continuous Integration', 'CI'), ('Continuous Integration', 'Continuous Integration Pipeline'), ('Continuous Integration', 'CI Pipeline'),
('Continuous Delivery', 'CD'), ('Continuous Delivery', 'Continuous Deployment'), ('Continuous Delivery', 'CD Pipeline'),
('Site Reliability Engineering', 'SRE'), ('Site Reliability Engineering', 'Site Reliability'), ('Site Reliability Engineering', 'Reliability Engineering'),
('PostgreSQL', 'Postgres'), ('PostgreSQL', 'Postgre SQL'), ('PostgreSQL', 'PGSQL'),
('Microsoft SQL Server', 'SQL Server'), ('Microsoft SQL Server', 'MSSQL'), ('Microsoft SQL Server', 'MS SQL'),
('MongoDB', 'Mongo'), ('MongoDB', 'Mongo DB'), ('MongoDB', 'Mongo Database'),
('Google BigQuery', 'BigQuery'), ('Google BigQuery', 'Big Query'), ('Google BigQuery', 'GCP BigQuery'),
('ETL Development', 'ETL'), ('ETL Development', 'Extract Transform Load'), ('ETL Development', 'ETL Pipelines'),
('Business Intelligence', 'BI'), ('Business Intelligence', 'BI Analytics'), ('Business Intelligence', 'Business Analytics'),
('Microsoft Power BI', 'Power BI'), ('Microsoft Power BI', 'PowerBI'), ('Microsoft Power BI', 'MS Power BI'),
('Artificial Intelligence', 'AI'), ('Artificial Intelligence', 'Artificial Intelligence Systems'), ('Artificial Intelligence', 'Applied AI'),
('Machine Learning', 'ML'), ('Machine Learning', 'Machine-Learning'), ('Machine Learning', 'Applied Machine Learning'),
('Deep Learning', 'DL'), ('Deep Learning', 'Deep Neural Learning'), ('Deep Learning', 'Deep-Learning'),
('Generative AI', 'GenAI'), ('Generative AI', 'Gen AI'), ('Generative AI', 'Generative Artificial Intelligence'),
('Large Language Models', 'LLM'), ('Large Language Models', 'LLMs'), ('Large Language Models', 'Large Language Model'),
('Natural Language Processing', 'NLP'), ('Natural Language Processing', 'Language AI'), ('Natural Language Processing', 'Computational Linguistics'),
('Retrieval-Augmented Generation', 'RAG'), ('Retrieval-Augmented Generation', 'Retrieval Augmented Generation'), ('Retrieval-Augmented Generation', 'Grounded Generation'),
('Model Context Protocol', 'MCP'), ('Model Context Protocol', 'Model-Context Protocol'), ('Model Context Protocol', 'AI Model Context Protocol'),
('Convolutional Neural Networks', 'CNN'), ('Convolutional Neural Networks', 'CNNs'), ('Convolutional Neural Networks', 'Convolutional Network'),
('Recurrent Neural Networks', 'RNN'), ('Recurrent Neural Networks', 'RNNs'), ('Recurrent Neural Networks', 'Recurrent Network'),
('Geographic Information Systems', 'GIS'), ('Geographic Information Systems', 'Geospatial Information Systems'), ('Geographic Information Systems', 'Geographic Information System'),
('Building Information Modeling', 'BIM'), ('Building Information Modeling', 'Building Information Modelling'), ('Building Information Modeling', 'Building Model Management'),
('Computer-Aided Design', 'CAD'), ('Computer-Aided Design', 'Computer Aided Design'), ('Computer-Aided Design', 'Digital Drafting'),
('Computer-Aided Manufacturing', 'CAM'), ('Computer-Aided Manufacturing', 'Computer Aided Manufacturing'), ('Computer-Aided Manufacturing', 'Digital Manufacturing'),
('Finite Element Analysis', 'FEA'), ('Finite Element Analysis', 'Finite Element Method'), ('Finite Element Analysis', 'Finite Element Modelling'),
('Computational Fluid Dynamics', 'CFD'), ('Computational Fluid Dynamics', 'Computational Fluid Modeling'), ('Computational Fluid Dynamics', 'Fluid Flow Simulation'),
('Geometric Dimensioning and Tolerancing', 'GD&T'), ('Geometric Dimensioning and Tolerancing', 'Geometric Dimensioning & Tolerancing'), ('Geometric Dimensioning and Tolerancing', 'Geometric Tolerancing'),
('Programmable Logic Controllers', 'PLC'), ('Programmable Logic Controllers', 'PLCs'), ('Programmable Logic Controllers', 'Programmable Logic Controller'),
('Environmental, Social, and Governance', 'ESG'), ('Environmental, Social, and Governance', 'Environmental Social Governance'), ('Environmental, Social, and Governance', 'ESG Management'),
('International Financial Reporting Standards', 'IFRS'), ('International Financial Reporting Standards', 'International Accounting Standards'), ('International Financial Reporting Standards', 'IFRS Accounting'),
('Generally Accepted Accounting Principles', 'GAAP'), ('Generally Accepted Accounting Principles', 'US GAAP'), ('Generally Accepted Accounting Principles', 'Accounting Principles'),
('Enterprise Resource Planning', 'ERP'), ('Enterprise Resource Planning', 'Enterprise Planning System'), ('Enterprise Resource Planning', 'ERP Systems'),
('Customer Relationship Management', 'CRM'), ('Customer Relationship Management', 'Customer Relations Management'), ('Customer Relationship Management', 'CRM Systems'),
('Search Engine Optimization', 'SEO'), ('Search Engine Optimization', 'Search Optimisation'), ('Search Engine Optimization', 'Organic Search'),
('Search Engine Marketing', 'SEM'), ('Search Engine Marketing', 'Paid Search'), ('Search Engine Marketing', 'Search Marketing'),
('Conversion Rate Optimization', 'CRO'), ('Conversion Rate Optimization', 'Conversion Optimization'), ('Conversion Rate Optimization', 'Conversion Optimisation'),
('User Experience Design', 'UX Design'), ('User Experience Design', 'UX'), ('User Experience Design', 'Experience Design'),
('User Interface Design', 'UI Design'), ('User Interface Design', 'UI'), ('User Interface Design', 'Interface Design'),
('Diversity, Equity, and Inclusion', 'DEI'), ('Diversity, Equity, and Inclusion', 'Diversity Equity Inclusion'), ('Diversity, Equity, and Inclusion', 'Diversity and Inclusion'),
('Cardiopulmonary Resuscitation', 'CPR'), ('Cardiopulmonary Resuscitation', 'Cardiac Resuscitation'), ('Cardiopulmonary Resuscitation', 'Basic CPR'),
('English as a Second Language', 'ESL'), ('English as a Second Language', 'English Language Learning'), ('English as a Second Language', 'English for Non-Native Speakers'),
('Virtual Private Networks', 'VPN'), ('Virtual Private Networks', 'VPNs'), ('Virtual Private Networks', 'Virtual Private Network'),
('Identity and Access Management', 'IAM'), ('Identity and Access Management', 'Identity Management'), ('Identity and Access Management', 'Access Management'),
('Security Information and Event Management', 'SIEM'), ('Security Information and Event Management', 'Security Event Management'), ('Security Information and Event Management', 'Security Information Management'),
('Governance, Risk, and Compliance', 'GRC'), ('Governance, Risk, and Compliance', 'Governance Risk Compliance'), ('Governance, Risk, and Compliance', 'Risk and Compliance'),
('JSON Web Tokens', 'JWT'), ('JSON Web Tokens', 'JWTs'), ('JSON Web Tokens', 'JSON Web Token'),
('Object-Oriented Programming', 'OOP'), ('Object-Oriented Programming', 'Object Oriented Programming'), ('Object-Oriented Programming', 'Object-Oriented Development'),
('Test-Driven Development', 'TDD'), ('Test-Driven Development', 'Test Driven Development'), ('Test-Driven Development', 'Test-First Development'),
('Behavior-Driven Development', 'BDD'), ('Behavior-Driven Development', 'Behaviour-Driven Development'), ('Behavior-Driven Development', 'Behavior Driven Development'),
('Quality Assurance', 'QA'), ('Quality Assurance', 'Software QA'), ('Quality Assurance', 'Quality Testing'),
('Key Performance Indicators', 'KPI'), ('Key Performance Indicators', 'KPIs'), ('Key Performance Indicators', 'Performance Indicators')
ON CONFLICT DO NOTHING;

-- One catalog entry above is intentionally represented by its industry term.
-- Add it if an older database did not already contain it.
INSERT INTO "skill" ("name") VALUES ('Key Performance Indicators')
ON CONFLICT ("name") DO NOTHING;

WITH "alias_candidates" AS (
    SELECT
        "skill"."id" AS "skillId",
        "override"."alias",
        1 AS "priority"
    FROM "_skill_alias_override" AS "override"
    JOIN "skill" ON "skill"."name" = "override"."skillName"

    UNION ALL

    SELECT "skill"."id", lower("skill"."name"), 10
    FROM "skill"
    JOIN "_skill_seed" ON "_skill_seed"."name" = "skill"."name"

    UNION ALL

    SELECT
        "skill"."id",
        regexp_replace(lower("skill"."name"), '[^a-z0-9+#]+', '', 'g'),
        20
    FROM "skill"
    JOIN "_skill_seed" ON "_skill_seed"."name" = "skill"."name"

    UNION ALL

    SELECT
        "skill"."id",
        trim(BOTH '-' FROM regexp_replace(lower("skill"."name"), '[^a-z0-9+#]+', '-', 'g')),
        30
    FROM "skill"
    JOIN "_skill_seed" ON "_skill_seed"."name" = "skill"."name"

    UNION ALL

    SELECT "skill"."id", lower("skill"."name") || ' skill', 40
    FROM "skill"
    JOIN "_skill_seed" ON "_skill_seed"."name" = "skill"."name"

    UNION ALL

    SELECT "skill"."id", lower("skill"."name") || ' training', 50
    FROM "skill"
    JOIN "_skill_seed" ON "_skill_seed"."name" = "skill"."name"
),
"deduplicated_candidates" AS (
    SELECT DISTINCT ON ("skillId", lower("alias"))
        "skillId",
        "alias",
        "priority"
    FROM "alias_candidates"
    WHERE length(trim("alias")) > 0
    ORDER BY "skillId", lower("alias"), "priority"
),
"ranked_candidates" AS (
    SELECT
        "skillId",
        "alias",
        row_number() OVER (
            PARTITION BY "skillId"
            ORDER BY "priority", length("alias"), "alias"
        ) AS "aliasRank"
    FROM "deduplicated_candidates"
)
INSERT INTO "skill_alias" ("skillId", "alias")
SELECT "skillId", "alias"
FROM "ranked_candidates"
WHERE "aliasRank" <= 3
ON CONFLICT ("alias") DO NOTHING;

DROP TABLE "_skill_alias_override";
DROP TABLE "_skill_seed";
