export {
    addDiscussionApi,
    addFileToPostApi,
    addPostApi,
    addRateDiscussionApi,
    addRatePostApi,
    deleteDiscussionApi,
    deletePostApi,
    generatePostFieldApi,
    getChildrenDiscussionsApi,
    getCourseApi,
    getCoursesApi,
    getDiscussionByIdApi,
    getDiscussionsByPostApi,
    getFilesOfPostApi,
    getPostApi,
    getPostsByUsernameApi,
    getPostsOfCourseApi,
    getProfileByIdApi,
    getRateDiscussionApi,
    getRatePostApi,
    getUserFoldersApi,
    removeFileToPostApi,
    updateDiscussionApi,
    updatePostApi,
    updateRateDiscussionApi,
    updateRatePostApi,
} from "@/shared/api";
